# Gems
gems: [jekyll-paginate]

# Site settings
title: Space 14
header-img: img/home-bg.jpg
email: zjshen14@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl:
url: "http://zjshen.github.io"
twitter_username:
github_username: zjshen
facebook_username: zjshen
linkedin_username: zjshen

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
